//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public string Fuente { get; set; }
        public string Descripcion { get; set; }
        public string Etiquetas { get; set; }
        public string Url { get; set; }
        public string Tipo { get; set; }
        public string Imagen { get; set; }
        public string Autor { get; set; }
        public string Especies { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Formato { get; set; }
    }
}
