//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacion()
        {
            this.cotizacionDetalle = new HashSet<cotizacionDetalle>();
        }
    
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdCamion { get; set; }
        public int DiaSemana { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<bool> Enviado { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Observaciones { get; set; }
    
        public virtual camion camion { get; set; }
        public virtual distribuidores distribuidores { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacionDetalle> cotizacionDetalle { get; set; }
    }
}
