//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class distribuidores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public distribuidores()
        {
            this.cotizacion = new HashSet<cotizacion>();
        }
    
        public int Id { get; set; }
        public string No_cte { get; set; }
        public string Planta { get; set; }
        public string Nombre_fact { get; set; }
        public string Nombre_com { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string C_P { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Mail { get; set; }
        public string Categoria { get; set; }
        public string Horario { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Mapa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacion> cotizacion { get; set; }
    }
}
