//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaltaDBEntities : DbContext
    {
        public MaltaDBEntities()
            : base("name=MaltaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalles_producto> detalles_producto { get; set; }
        public virtual DbSet<especies> especies { get; set; }
        public virtual DbSet<marcas> marcas { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<lineas> lineas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<detalles_salud> detalles_salud { get; set; }
        public virtual DbSet<salud> salud { get; set; }
        public virtual DbSet<blog> blog { get; set; }
        public virtual DbSet<distribuidores> distribuidores { get; set; }
        public virtual DbSet<camion> camion { get; set; }
        public virtual DbSet<correo> correo { get; set; }
        public virtual DbSet<cotizacion> cotizacion { get; set; }
        public virtual DbSet<medidas> medidas { get; set; }
        public virtual DbSet<planta> planta { get; set; }
        public virtual DbSet<plantilla> plantilla { get; set; }
        public virtual DbSet<precios> precios { get; set; }
        public virtual DbSet<puesto> puesto { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<cotizacionDetalle> cotizacionDetalle { get; set; }
        public virtual DbSet<visitas> visitas { get; set; }
    }
}
