//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salud
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public string Tipo { get; set; }
        public string Indicaciones { get; set; }
        public string Contraindicaciones { get; set; }
        public string Administracion { get; set; }
        public string Interaccion { get; set; }
        public string Reacciones { get; set; }
        public string Uso { get; set; }
        public string Brochure { get; set; }
        public string Vademecum { get; set; }
        public string Video { get; set; }
        public string Params_dist { get; set; }
    }
}
